# Generated by Django 2.2 on 2020-10-17 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200913_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='noderun',
            name='function',
            field=models.CharField(choices=[('select_columns', 'Select columns'), ('add_column', 'Add column'), ('merge_tables', 'Merge tables'), ('join_tables', 'Join tables'), ('filter', 'Filter'), ('sort', 'Sort'), ('to_number', 'To Number'), ('math_expression', 'Mathematical expression'), ('summarize', 'Summarize'), ('is_nan', 'Is NaN'), ('text_template', 'Text template'), ('http_request', 'HTTP Request'), ('read_csv_from_url', 'Read CSV from URL'), ('read_google_sheet', 'Read Google Sheet'), ('query_postgresql', 'Query Postrgresql Database'), ('import_google_analytics', 'Import Google Analytics data'), ('send_pushbullet_notification', 'Send Pushbullet notification'), ('send_slack_message', 'Send message to slack'), ('write_google_sheet', 'Write to Google Sheet')], default='filter', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='noderun',
            name='name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='node',
            name='function',
            field=models.CharField(choices=[('select_columns', 'Select columns'), ('add_column', 'Add column'), ('merge_tables', 'Merge tables'), ('join_tables', 'Join tables'), ('filter', 'Filter'), ('sort', 'Sort'), ('to_number', 'To Number'), ('math_expression', 'Mathematical expression'), ('summarize', 'Summarize'), ('is_nan', 'Is NaN'), ('text_template', 'Text template'), ('http_request', 'HTTP Request'), ('read_csv_from_url', 'Read CSV from URL'), ('read_google_sheet', 'Read Google Sheet'), ('query_postgresql', 'Query Postrgresql Database'), ('import_google_analytics', 'Import Google Analytics data'), ('send_pushbullet_notification', 'Send Pushbullet notification'), ('send_slack_message', 'Send message to slack'), ('write_google_sheet', 'Write to Google Sheet')], max_length=40),
        ),
    ]
