class NODE_CATEGORIES:
    TRIGGER = "Trigger"
    CONTROL_FLOW = "Control Flow"
    TABLE = "Table"
    OBJECT = "Object"
    ARRAY = "Array"
    MATH = "Math"
    LOGIC = "Logic"
    TEXT = "Text"
    INTELLIGENCE = "Intelligence"
    DATA_IN = "Data sources"
    DATA_OUT = "Data destinations"
