# Generated by Django 3.2.7 on 2021-10-08 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credentials',
            name='credentials',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='oauth2credentials',
            name='token',
            field=models.JSONField(),
        ),
    ]
