export const userConstants = {
  GET_INFO_START: 'GET_INFO_START',
  GET_INFO_FAILURE: 'GET_INFO_FAILURE',
  GET_INFO_SUCCESS: 'GET_INFO_SUCCESS',
  LOGIN_START: 'LOGIN_START',
  LOGIN_FAILURE: 'LOGIN_FAILURE',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  AUTO_LOGIN_START: 'AUTO_LOGIN_START',
  AUTO_LOGIN_FAILURE: 'AUTO_LOGIN_FAILURE',
  AUTO_LOGIN_SUCCESS: 'AUTO_LOGIN_SUCCESS',
  SIGNUP_START: 'SIGNUP_START',
  SIGNUP_FAILURE: 'SIGNUP_FAILURE',
  SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',
  LOGOUT: 'LOGOUT'
};