from .oauth2.oauth2_providers import OAUTH2_PROVIDERS, OAUTH2_PROVIDERS_CHOICE
from .database.database_providers import DATABASE_PROVIDERS, DATABASE_PROVIDERS_CHOICE

SERVICE_PROVIDERS = {**OAUTH2_PROVIDERS, **DATABASE_PROVIDERS}

SERVICE_PROVIDERS_CHOICE = OAUTH2_PROVIDERS_CHOICE + DATABASE_PROVIDERS_CHOICE
